# -*- coding: utf-8 -*-
"""Modelo 1 - BGE base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VgSoDyIktrjfBeL13jTq0EfpL4rGwZVe
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. Instalar as bibliotecas necessárias
!pip install transformers accelerate bitsandbytes sentence-transformers Pillow datasets
!pip install -q git+https://github.com/huggingface/peft.git  # PEFT é útil para modelos grandes

# 2. Clonar o repositório ScreenPipe
!git clone https://github.com/mediar-ai/screenpipe.git
# %cd screenpipe
!ls # Verifique os diretórios clonados

# Commented out IPython magic to ensure Python compatibility.
!pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer

# Modelo 1: BGE-base para embeddings
embed_model_name = "BAAI/bge-base-en-v1.5"
embed_model = SentenceTransformer(embed_model_name, device="cuda")

print("Modelo de embeddings carregado:", embed_model_name)

import os

# %cd /content/screenpipe

# extensões que queremos indexar
EXTENSOES_VALIDAS = (".rs", ".ts", ".tsx", ".js", ".md", ".toml", ".yaml", ".yml")

docs = []   # cada item: {"texto": ..., "arquivo": ..., "modulo": ...}

for root, dirs, files in os.walk("."):
    for fname in files:
        if fname.endswith(EXTENSOES_VALIDAS):
            path = os.path.join(root, fname)
            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    text = f.read()
            except Exception:
                continue

            # módulo = nome da primeira pasta depois de ./  (ex: ./screenpipe-core/src/... -> screenpipe-core)
            rel = path.lstrip("./")
            modulo = rel.split(os.sep)[0] if os.sep in rel else rel

            # dividir em chunks de ~1000 caracteres
            CHUNK_SIZE = 1000
            for i in range(0, len(text), CHUNK_SIZE):
                chunk = text[i:i+CHUNK_SIZE]
                if chunk.strip():
                    docs.append({
                        "texto": chunk,
                        "arquivo": path,
                        "modulo": modulo,
                        "offset": i,  # onde começa no arquivo
                    })

print(f"Total de chunks criados: {len(docs)}")
print("Exemplo de doc:", docs[0]["arquivo"], "| módulo:", docs[0]["modulo"])

from tqdm.auto import tqdm

corpus_texts = [d["texto"] for d in docs]

# gera embeddings normalizados (bom pra cosine similarity)
embeddings = embed_model.encode(
    corpus_texts,
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Shape dos embeddings:", embeddings.shape)

import numpy as np
from sentence_transformers.util import cos_sim

def buscar_trechos(query, modulo=None, top_k=5):
    """
    query: texto da busca (ex: 'captura de tela', 'API de busca', 'pipes/plugins')
    modulo: se quiser filtrar por 'screenpipe-core', 'screenpipe-server', etc.
    top_k: quantos trechos retornar
    """
    # embedding da consulta
    q_emb = embed_model.encode([query], normalize_embeddings=True)[0]

    # similaridade com todos os chunks
    scores = cos_sim(q_emb, embeddings)[0].cpu().numpy()

    # se quiser filtrar por módulo:
    indices_validos = list(range(len(docs)))
    if modulo:
        indices_validos = [i for i, d in enumerate(docs) if d["modulo"] == modulo]

    # pegar só os scores desses índices
    scores_filtrados = np.array([scores[i] for i in indices_validos])
    top_idx_local = scores_filtrados.argsort()[::-1][:top_k]

    resultados = []
    for local in top_idx_local:
        idx_global = indices_validos[local]
        d = docs[idx_global]
        resultados.append({
            "score": float(scores[idx_global]),
            "arquivo": d["arquivo"],
            "modulo": d["modulo"],
            "offset": d["offset"],
            "texto": d["texto"],
        })
    return resultados


resultados = buscar_trechos(
    "screen capture core pipeline",
    modulo="screenpipe-core",
    top_k=3
)

for r in resultados:
    print("="*80)
    print("Arquivo:", r["arquivo"])
    print("Módulo:", r["modulo"], "| score:", round(r["score"], 3))
    print(r["texto"][:800])


resultados1 = buscar_trechos(
    "search api http server sse",
    modulo="screenpipe-server",
    top_k=3
)

for r in resultados1:
    print("="*80)
    print("Arquivo:", r["arquivo"])
    print("Módulo:", r["modulo"], "| score:", round(r["score"], 3))
    print(r["texto"][:800])