# -*- coding: utf-8 -*-
"""Modelo 2 - Mistral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10esm57pi0ZBuX8wt06fGqnEnpYGPye-O
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. Instalar as bibliotecas necessárias
!pip install transformers accelerate bitsandbytes sentence-transformers Pillow datasets
!pip install -q git+https://github.com/huggingface/peft.git  # PEFT é útil para modelos grandes

# 2. Clonar o repositório ScreenPipe
!git clone https://github.com/mediar-ai/screenpipe.git
# %cd screenpipe
!ls # Verifique os diretórios clonados

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "mistralai/Mistral-7B-Instruct-v0.3"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model2 = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto" if torch.cuda.is_available() else None,
)

print("Dispositivo:", model2.device)


def mistral_analisar_texto(texto, question_extra=""):
    texto = texto[:4000]

    prompt = f"""
Você é um arquiteto de software experiente. Analise o código/trecho abaixo
do projeto Screenpipe e responda:

1. Qual é a responsabilidade principal desse módulo?
2. Em que parte da arquitetura ele se encaixa (core/captura, server/API, pipes/plugins, storage/db)?
3. Com quais outros componentes ele provavelmente interage?
4. {question_extra}

Código:
```rust
{texto}
"""
    inputs = tokenizer(prompt, return_tensors="pt").to(model2.device)

    with torch.no_grad():
        out = model2.generate(
            **inputs,
            max_new_tokens=700,
            pad_token_id=tokenizer.eos_token_id,
            do_sample=False,   # determinístico
        )

    return tokenizer.decode(out[0], skip_special_tokens=True)


with open("screenpipe-server/src/server.rs") as f:
    code = f.read()

print(mistral_analisar_texto(
    code,
    question_extra="Destaque os endpoints de streaming e de busca."
))

